// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/ProgramData/VSCode/Python/3DRE_frontend-/3DRE_frontend-/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'D:/ProgramData/VSCode/Python/3DRE_frontend-/3DRE_frontend-/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/ProgramData/VSCode/Python/3DRE_frontend-/3DRE_frontend-/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
