// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/david/develop/3DRe/front/3dre/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/home/david/develop/3DRe/front/3dre/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/home/david/develop/3DRe/front/3dre/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
